#!/usr/bin/env node

var study = '';

var args = process.argv.slice(2)
var arg = args[0]

if (arg == '--version') {
        console.log(pkg.version)
        process.exit(0)
}

process.stdin.on('data', function (data) {
        study += data;
});

process.stdin.resume();

process.stdin.on('end', function () {
        json = JSON.parse(study);
        process.stdout.write(JSON.stringify(json[0]) + '\n')
});

