--  createtab_stmt
----------------------------------------------------------------------
 CREATE EXTERNAL TABLE `studies`(
 `nct_id` string,
 `nlm_download_date_description` string,
 `first_received_date` string,
 `last_changed_date` string,
 `first_received_results_date` string,
 `received_results_disposit_date` string,
 `study_first_submitted_date` string,
 `results_first_submitted_date` string,
 `disposition_first_submitted_date` string,
 `last_update_submitted_date` string,
 `study_first_submitted_qc_date` string,
 `study_first_posted_date` string,
 `study_first_posted_date_type` string,
 `results_first_submitted_qc_date` string,
 `results_first_posted_date` string,
 `results_first_posted_date_type` string,
 `disposition_first_submitted_qc_date` string,
 `disposition_first_posted_date` string,
 `disposition_first_posted_date_type` string,
 `last_update_submitted_qc_date` string,
 `last_update_posted_date` string,
 `last_update_posted_date_type` string,
 `start_month_year` string,
 `start_date_type` string,
 `start_date` string,
 `verification_month_year` string,
 `verification_date` string,
 `completion_month_year` string,
 `completion_date_type` string,
 `completion_date` string,
 `primary_completion_month_year` string,
 `primary_completion_date_type` string,
 `primary_completion_date` string,
 `target_duration` string,
 `study_type` string,
 `acronym` string,
 `baseline_population` string,
 `brief_title` string,
 `official_title` string,
 `overall_status` string,
 `last_known_status` string,
 `phase` string,
 `enrollment` bigint,
 `enrollment_type` string,
 `source` string,
 `limitations_and_caveats` string,
 `number_of_arms` bigint,
 `number_of_groups` bigint,
 `why_stopped` string,
 `has_expanded_access` string,
 `expanded_access_type_individual` string,
 `expanded_access_type_intermediate` string,
 `expanded_access_type_treatment` string,
 `has_dmc` string,
 `is_fda_regulated_drug` string,
 `is_fda_regulated_device` string,
 `is_unapproved_device` string,
 `is_ppsd` string,
 `is_us_export` string,
 `biospec_retention` string,
 `biospec_description` string,
 `plan_to_share_ipd` string,
 `plan_to_share_ipd_description` string,
 `created_at` string,
 `updated_at` string)
 PARTITIONED BY (
 `partition_0` string)
 ROW FORMAT DELIMITED
 FIELDS TERMINATED BY '|'
 STORED AS INPUTFORMAT
 'org.apache.hadoop.mapred.TextInputFormat'
 OUTPUTFORMAT
 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
 LOCATION
 's3://datainsights-in/clinicaltrials/aact/studies/'
 TBLPROPERTIES (
 'CrawlerSchemaDeserializerVersion'='1.0',
 'CrawlerSchemaSerializerVersion'='1.0',
 'UPDATED_BY_CRAWLER'='CT',
 'averageRecordSize'='747',
 'classification'='csv',
 'columnsOrdered'='true',
 'compressionType'='none',
 'delimiter'='|',
 'exclusions'='[\"s3://datainsights-in/clinicaltrials/aact/*.zip\"]',
 'objectCount'='1',
 'recordCount'='251391',
 'sizeKey'='187789699',
 'skip.header.line.count'='1',
 'typeOfData'='file')
