 CREATE EXTERNAL TABLE `actrn_studies`(
 `trial_id` string,
 `ethics_application_status` string,
 `date_submitted` string,
 `date_registered` string,
 `date_last_updated` string,
 `type_of_registration` string,
 `public_title` string,
 `scientific_title` string,
 `secondary_id` array<string>,
 `UTN` string,
 `trial_acronym` string,
 `linked_study_record` string,
 `health_conditions_or_problems_studied`  array<string>,
 `Condition_category` array<string>,
 `study_type` string,
 `Primary_Registry` string,
 `Target_follow_up_duration` string,
 `Target_follow_up_type` string,
 `Description_of_intervention(s)/exposure` string,
 `Comparator/control_treatment` string,
 `Control_group` string,
 `Outcome` Map<string, Array<String>>,
 `Key_inclusion_criteria` string,
 `Minimum_age` string,
 `Maximum_age` string,
 `Can_healthy_volunteers_participate?` string,
 `Key_exclusion_criteria` string,
 `study_design` string,
 `Recruitment_status` string,
 `Date_of_first_participant_enrolment` Struct<Anticipated:string,Actual:string>,
 `Date_of_last_participant_enrolment` Struct<Anticipated:string,Actual:string>,
 `Date_of_last_data_collection` Struct<Anticipated:string,Actual:string>,
 `Sample_Size` Struct<Target:string,Accrual_to_date:string,Final:string>,
 `Recruitment_outside_Australia` array<string>,
 `Recruitment_state` array<string>,
 `Recruitment_Inside_Australia` array<string>,
 `Funding&Sponsors` Map<string, Array<String>>,
 `Ethics_approval` struct<Ethics_application_status:array<string>,EthicsComitteDetails:Array<String>>,
 `Summary`  Struct<Brief_summary:string,Trial_website:string,Trial_related_presentations_publications:string,Public_notes:string>,
 `Principal_investigator`  Struct<name:string,address:string,Country:string,Phone:string,Fax:string,Email:string>,
 `Contact_person_for_public_queries`  Struct<name:string,address:string,Country:string,Phone:string,Fax:string,Email:string>,
 `Contact_person_for_scientific_queries`  Struct<name:string,address:string,Country:string,Phone:string,Fax:string,Email:string>
 )
  ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
      LOCATION 's3://hsdlc-results/actrn-adapter/json'
      TBLPROPERTIES (
      'ignore.malformed.json'= 'true'
      );