CREATE EXTERNAL TABLE `cris_studies`(
 `cris_registration_number` string,
  `unique_protocol_id` string,
  `public_or_brief_title` string,
  `scientific_title` string,
  `mfds_regulated_study` string,
  `registered_at_other_registry` string,
  `board_approval_status` string,
  `board_approval_number` string,
  `approval_date` string,
 `institutional_review_board`struct<name:string,adress:string,telephone:string>,
 `contact_for_scientific_queries`struct<name:string,title:string,affiliation:string,address:string>,
 `contact_for_public_queries`struct<name:string,title:string,affiliation:string,address:string>,
 `contact_person_for_updating_Info`struct<name:string,title:string,affiliation:string,address:string>,
 `data_monitoring_committee` string,
 `study_site`  string,
 `overall_recruitment_status`  string,
 `date_of_first_enrollment`  string,
 `target_number_of_participant` string,
 `primary_completion_date`  string,
 `study_completion_date` string,
 `sites` array<map<string,string>>,
 `source_of_monetary_or_material_support` array<map<string,string>>,
 `sponsor_organisation` array<map<string,string>>,
 `lay_summary` string,
 `study_type` string,
 `study_purpose` string,
 `phase` string,
 `intervention_model` string,
 `blinding_or_masking` string,
 `allocation` string,
 `intervention_type` string,
 `intervention_description` string,
 `number_of_arms` string,
 `arm` array<map<string,string>>,
`Observational_Study_Model`  string,
`TimePerspective` string ,
`TargetNumberOfParticipant` string,
`Cohort_GroupNumber ` string,
`Cohortgroup` array<map<string,string>>,
 `BiospecimenCollection`  string,
 `BiospecimenDescription`  string,
 `StudyPopulationDesc` string,
 `SamplingMethod` string,
 `conditions_problems` string,
 `rare_disease` string,
 `inclusion_criteria` struct<gender:string,age:string,description:string>,
 `exclusion_criteria` string,
 `healthy_volunteers` string,
 `type_of_primary_income` string,
 `primary_outcome` array<map<string,string>>,
 `secondary_outcome` array<map<string,string>>,
 `result_registered` string,
 `sharing_statement` string,
 `time_of_sharing` string,
 `way_of_sharing` string,
 `SEQ_NUMBER` int
 )
  ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
      LOCATION 's3://hsdlc-results/cristr-adapter/studies/json'
      TBLPROPERTIES (
      'ignore.malformed.json'= 'true'
      );