 CREATE EXTERNAL TABLE `ctri_studies_temp`(
 `ctri_number` string,
 `registered_on` string,
 `last_modified_on` string,
 `pg_thesis` string,
 `type_of_trial` string,
 `type_of_study` string,
 `study_design` string,
 `public_title` string,
 `scientific_title` string,
 `secondary_ids` struct<secondary_id:string,
                   identifier:string> ,
 `pi_or_tc` struct<name:string,
                   designation:string,
                   affiliation:string,
                   address:string,
                   phone:string,
                   fax:string,
                   email:string> ,
 `scientific_query_contact` struct<name:string,
                   designation:string,
                   affiliation:string,
                   address:string,
                   phone:string,
                   fax:string,
                   email:string> ,
 `public_query_contact` struct<name:string,
                   designation:string,
                   affiliation:string,
                   address:string,
                   phone:string,
                   fax:string,
                   email:string> ,
 `support_source` string,
 `primary_sponsor` struct<name:string,
                   address:string,
                   type:string> ,
 `secondary_sponsor` struct<name:string,
                   address:string> ,
 `countries_of_recruitment` string,
 `sites`array<struct<name_of_principal_investigator:string,
                   name_of_site:string,
                   site_address:string,
                   phone_fax_email:string>>,
 `ethics_committee` array<struct<name_of_committee:string,
                   approval_status:string,
                   site_address:string,
                   phone_fax_email:string>>,
 `regulatory_clearance_status` struct<name:string,
                   status:string> ,
 `condition_or_problems` struct<health_type:string,
                   condition:string> ,
 `intervention_or_comparator_agent` array<struct<type:string,
                   name:string,
                   details:string>>,
 `inclusion_criteria` struct<age_from:string,
                   age_to:string,
                   gender:string,
                   details:string> ,
 `exclusion_criteria` struct<details:string>,
 `method_of_generating_random_sequence` string,
 `method_of_concealment` string,
 `blinding_and_masking` string,
 `primary_outcome` struct<outcome:string,
                   timepoints:string>,
 `secondary_outcome` struct<outcome:string,
                   timepoints:string>,
 `target_sample_size` struct<total_sample_size:string,
                   sample_size_from_india:string,
                   final_enrollment_numbers_achieved_total:string,
                   final_enrollment_numbers_achieved_total:string>,
 `phase` string,
 `date_of_first_enrollment_india` string,
 `date_of_completion_india` string,
 `date_of_first_enrollment_global` string,
 `date_of_completion_global` string,
 `estimated_duration` struct<years:string,
                   months:string,
                   days:string>,
 `recruitment_status_global` string,
 `recruitment_status_india` string,
 `publication_details` string,
 `brief_summary` string)
  ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
      LOCATION 's3://hsdlc-results/ctri-adapter/studies/json'
      TBLPROPERTIES (
      'ignore.malformed.json'= 'true'
      );