CREATE EXTERNAL TABLE `ntr_studies`(
`acronym` string,
`contact` Struct<email:string,firstName:string,institute:string,lastName:string,phone:string>,
`control` string,
`criteriaEx` string,
`criteriaIn` string,
`dateRegistered` string,
`dateStart` string,
`dateStop` string,
`diseases` string,
`fundingSources` string,
`groupTypes` string,
`grouping` string,
`hypothesis` string,
`id` string,
`idFull` string,
`idOld` string,
`idOldFull`string,
`idSource` string,
`idString` string,
`interventions` string,
`ipd` string,
`ipdDescription` string,
`isrctn` string,
`issueingBody` string,
`key` string,
`outcomeSecondary` string,
`pubStatus` string,
`publications` string,
`randomised` string,
`registrant` Struct<email:string,firstName:string,lastName:string,phone:string,search:string,userId:string>,
`sponsors` string,
`status` string,
`studyType` string,
`summary` string,
`targetSize` string,
`timePoints` string,
`title` string,
`titleScientific` string,
`url` string,
`userId` string,
`userIdOld` string
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
      LOCATION 's3://hsdlc-results/ntr-adapter/studies/json'
      TBLPROPERTIES (
      'ignore.malformed.json'= 'true'
      );
