create view v_fda_devices as
select d.PrimaryDI as primarydi,
       publicDeviceRecordKey,
       publicVersionStatus,
       deviceRecordStatus,
       publicVersionNumber,
       publicVersionDate,
       devicePublishDate,
       deviceCommDistributionEndDate,
       deviceCommDistributionStatus,
       brandName,
       versionModelNumber,
       catalogNumber,
       dunsNumber,
       companyName,
       deviceCount,
       deviceDescription,
       DMExempt,
       premarketExempt,
       deviceHCTP,
       deviceKit,
       deviceCombinationProduct,
       singleUse,
       lotBatch,
       serialNumber,
       manufacturingDate,
       expirationDate,
       donationIdNumber,
       labeledContainsNRL,
       labeledNoNRL,
       MRISafetyStatus,
       rx,
       otc,
       deviceSterile,
       sterilizationPriorToUse,
       phone,
       phoneExtension,
       email,
       sizeType,
       sizeUnit,
       sizeValue,
       sizeText
from fda_devices d,
     fda_contacts c,
     fda_device_sizes s
where d.primarydi = c.primarydi
  and c.primarydi = s.primarydi