create view v_fda_devices as
select d.PrimaryDI as primarydi,
       publicdevicerecordkey,
       publicversionstatus,
       devicerecordstatus,
       publicversionnumber,
       publicversiondate,
       devicepublishdate,
       devicecommdistributionenddate,
       devicecommdistributionstatus,
       brandname,
       versionmodelnumber,
       catalognumber,
       dunsnumber,
       companyname,
       devicecount,
       devicedescription,
       dmexempt,
       premarketexempt,
       devicehctp,
       devicekit,
       devicecombinationproduct,
       singleuse,
       lotbatch,
       serialnumber,
       manufacturingdate,
       expirationdate,
       donationidnumber,
       labeledcontainsnrl,
       labelednonrl,
       mrisafetystatus,
       rx,
       otc,
       devicesterile,
       sterilizationpriortouse,
       phone,
       phoneextension,
       email,
       sizetype,
       sizeunit,
       sizevalue,
       sizetext
from fda_devices d,
     fda_contacts c,
     fda_device_sizes s
where d.primarydi = c.primarydi
  and c.primarydi = s.primarydi