create view v_icij_devices as
select
       e.id   as event_id,
       action,
       action_classification,
       action_level,
       action_summary,
       authorities_link,
       e.country as event_country,
       create_date,
       data_notes,
       date,
       date_initiated_by_firm,
       date_posted,
       date_terminated,
       date_updated,
       determined_cause,
       documents,
       icij_notes,
       e.number as event_number,
       reason,
       e.source as event_source,
       status,
       target_audience,
       type,
       uid,
       uid_hash,
       url,
       e.slug as event_slug,
       e.device_id as event_device_id,
       d.id   as device_id,
       classification,
       code,
       description,
       distributed_to,
       implanted,
       d.name as device_name,
       d.number as device_number,
       quantity_in_commerce,
       risk_class,
       d.slug as device_slug,
       d.country as device_country,
       d.manufacturer_id as device_manufacturer_id,
       m.id   as manufacturer_id,
       address,
       comment,
       m.name as manufacturer_name,
       parent_company,
       representative,
       m.slug as manufacturer_slug,
       m.source as manufacturer_source
from icij_devices d,
     icij_manufacturers m,
     icij_events e
where e.device_id = d.id
  and d.manufacturer_id = m.id;